CREATE DATABASE virtualdc

USE virtualdc

CREATE TABLE cadfun(
	CODFUN INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(40) NOT NULL,
	DEPTO CHAR(2),
	FUNCAO CHAR(20),
	SALARIO DECIMAL(10,2)
)

INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (12,'CARLOS ALBERTO','3','VENDEDOR',153000)
INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (15,'MARCOS HENRIQUE','2','GERENTE', 1985.75)
INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (9,'SOLANGE PACHECO','9','SUPERVISORA', 1599.51)
INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (1,'CELIA NASCIMENTO','1','SECRETARIA', 1200.50)
INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (7,'APARECIDA SILVA','3','SECRETARIA', 1200.50)
INSERT INTO cadfun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (6,'MARCELO SOUZA','3','ANALISTA', 2250.11)

INSERT INTO cadfun VALUES (2,'WILSON DE MACEDO','3','PROGRAMADOR',1050.00)
INSERT INTO cadfun VALUES (4,'CARLOS BASTOS','5','VENDEDOR',1530.00)
INSERT INTO cadfun VALUES (3,'ANA BASTOS','5','VENDEDORA',1530.00)
INSERT INTO cadfun VALUES (5,'AUGUSTO SOUZA','3','PROGRAMADOR',1050.00)
INSERT INTO cadfun VALUES (25,'PEDRO SILVA','3','SUPERVISOR',1599.51)
INSERT INTO cadfun VALUES (10,'PAULO DA SILVA','2','VENDEDOR',1530.00)


SELECT * FROM cadfun
SELECT NOME FROM cadfun
SELECT NOME, FUNCAO FROM cadfun
SELECT NOME FROM cadfun WHERE DEPTO = '3'
SELECT NOME, SALARIO FROM cadfun ORDER BY NOME DESC
SELECT DEPTO, NOME FROM cadfun ORDER BY DEPTO, NOME DESC
SELECT NOME FROM cadfun WHERE DEPTO = '3' ORDER BY NOME

SELECT * FROM cadfun WHERE CODFUN = '7'
UPDATE cadfun SET SALARIO = 2300.56 WHERE CODFUN = '7'
SELECT * FROM cadfun WHERE CODFUN = '7'

SELECT * FROM cadfun WHERE CODFUN = 3
UPDATE cadfun SET DEPTO = '3' WHERE CODFUN = 3
SELECT * FROM cadfun WHERE CODFUN = 3

SELECT * FROM cadfun
UPDATE cadfun SET SALARIO = SALARIO * 1.10
SELECT * FROM cadfun

SELECT * FROM cadfun WHERE DEPTO = '2'
DELETE cadfun WHERE DEPTO = '2'
SELECT * FROM cadfun WHERE DEPTO = '2'

SELECT * FROM cadfun WHERE CODFUN = 6
DELETE cadfun WHERE CODFUN = 6
SELECT * FROM cadfun WHERE CODFUN = 6

ALTER TABLE cadfun ADD ADMISSAO DATE
SELECT * FROM cadfun

UPDATE cadfun SET ADMISSAO = '15/01/2016' WHERE CODFUN = 2
UPDATE cadfun SET ADMISSAO = '21/10/1999' WHERE CODFUN = 3
UPDATE cadfun SET ADMISSAO = '21/10/2014' WHERE CODFUN = 4
UPDATE cadfun SET ADMISSAO = '26/04/2016' WHERE CODFUN = 5
UPDATE cadfun SET ADMISSAO = '10/05/1980' WHERE CODFUN = 7
UPDATE cadfun SET ADMISSAO = '15/02/2000' WHERE CODFUN = 9
UPDATE cadfun SET ADMISSAO = '21/12/2010' WHERE CODFUN = 12
UPDATE cadfun SET ADMISSAO = '21/12/2010' WHERE CODFUN = 25

SELECT * FROM cadfun

SELECT NOME, ADMISSAO FROM cadfun WHERE MONTH(ADMISSAO) = '12'

CREATE TABLE morto(
	CODFUN INT PRIMARY KEY,
	NOME VARCHAR(40),
	DEPTO CHAR(2),
	FUNCAO CHAR(20),
	SALARIO DECIMAL(10,2),
	ADMISSAO DATE
)

INSERT INTO morto
SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO FROM cadfun 
WHERE CODFUN = 12

DELETE cadfun WHERE CODFUN = 12

SELECT *
FROM cadfun
WHERE SALARIO = (SELECT SALARIO
				 FROM morto)

SELECT *
FROM cadfun
WHERE DEPTO = (SELECT DEPTO
				 FROM morto)
