--OPERADOR ARITMÉTICOS
SELECT NOME, SALARIO + 100 FROM cadfun
SELECT 2 + 3 * 5
SELECT (2 + 3) * 5

--OPERADOR RELACIONAL
SELECT * FROM cadfun WHERE DEPTO = '5'
SELECT * FROM cadfun WHERE FUNCAO = 'VENDEDOR'
SELECT * FROM cadfun WHERE SALARIO <= 1700

--OPERADOR LÓGICO
SELECT * FROM cadfun WHERE DEPTO = '3' AND FUNCAO = 'PROGRAMADOR'
SELECT * FROM cadfun WHERE DEPTO = '3' OR DEPTO = '5'
SELECT * FROM cadfun WHERE NOT FUNCAO = 'VENDEDOR'

ALTER TABLE cadfun ADD FILHOS SMALLINT
ALTER TABLE morto ADD FILHOS SMALLINT

SELECT NOME, FILHOS FROM cadfun
SELECT NOME, FILHOS FROM morto


UPDATE cadfun SET FILHOS = 1 WHERE CODFUN = 2
UPDATE cadfun SET FILHOS = 3 WHERE CODFUN = 3
UPDATE cadfun SET FILHOS = 2 WHERE CODFUN = 5
UPDATE cadfun SET FILHOS = 1 WHERE CODFUN = 9
UPDATE cadfun SET FILHOS = 4 WHERE CODFUN = 20
UPDATE cadfun SET FILHOS = 3 WHERE CODFUN = 25

SELECT CODFUN, NOME, FILHOS FROM cadfun WHERE FILHOS IS NULL