CREATE TABLE STATES
(
	StateID INT PRIMARY KEY,
	StateName VARCHAR(50),
	StateAbbrev CHAR(2)
)

--CRIANDO UM IDENTITY NA MÃO
CREATE SEQUENCE dbo.StateSeq
AS INT
START WITH 1
INCREMENT BY 1
GO

--Usando o IDENTITY criado
INSERT INTO STATES(StateID, StateAbbrev, StateName)
VALUES(NEXT VALUE FOR dbo.StateSeq, 'LA', 'Louisiana')

INSERT INTO STATES(StateID, StateAbbrev, StateName)
VALUES(NEXT VALUE FOR dbo.StateSeq, 'TX', 'Texas')

INSERT INTO STATES(StateID, StateAbbrev, StateName)
VALUES(NEXT VALUE FOR dbo.StateSeq, 'FL', 'Florida')

SELECT * FROM STATES


--MESCLAGEM DE DADOS
CREATE TABLE CIDADE_HOLANDA(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(50),
	UF VARCHAR(2)
)

CREATE TABLE CIDADE_BRASIL(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(50),
	UF VARCHAR(2)
)

INSERT INTO CIDADE_HOLANDA (Nome, UF) VALUES ('Amsterdan','A1')
INSERT INTO CIDADE_HOLANDA (Nome, UF) VALUES ('Amsterdon','A2')
INSERT INTO CIDADE_HOLANDA (Nome, UF) VALUES ('Amsterdbn','AM')
INSERT INTO CIDADE_HOLANDA (Nome, UF) VALUES ('Amsterdcn','AM')
INSERT INTO CIDADE_HOLANDA (Nome, UF) VALUES ('Amsterddn','AM')
INSERT INTO CIDADE_HOLANDA (Nome, UF) VALUES ('Amsterden','AM')

INSERT INTO CIDADE_BRASIL (Nome, UF) VALUES ('ERRADO','A1')
INSERT INTO CIDADE_BRASIL (Nome, UF) VALUES ('ERRADO','A2')
INSERT INTO CIDADE_BRASIL (Nome, UF) VALUES ('São Paulo','SP')
INSERT INTO CIDADE_BRASIL (Nome, UF) VALUES ('Rio de Janeiro','RJ')
INSERT INTO CIDADE_BRASIL (Nome, UF) VALUES ('Ceara','CE')
INSERT INTO CIDADE_BRASIL (Nome, UF) VALUES ('Minas Gerais','MG')

MERGE CIDADE_BRASIL destination
	USING CIDADE_HOLANDA source
		ON destination.UF = source.UF
	WHEN MATCHED THEN		
		UPDATE SET destination.Nome = source.Nome	
	WHEN NOT MATCHED BY TARGET THEN		
		INSERT (Nome, UF) VALUES(source.Nome, source.UF);
				

--FAZENDO AUDITORIA
--NO MOMENTO DE INSERIR
INSERT INTO CIDADE_HOLANDA(Nome, UF)
	OUTPUT inserted.Id, inserted.Nome, inserted.UF
VALUES('MAX VERSTAPEN','MX')

--NO MOMENTO DE FAZER ATUALIZAÇÃO
UPDATE CIDADE_HOLANDA
SET Nome = Nome + ' - Holanda', UF = 'MV'
	OUTPUT deleted.Nome AS OldName, deleted.UF AS OldUF,
		   inserted.Nome AS UpdateName, inserted.UF AS UpdateUF
WHERE ID = 7


--INSERINDO DADOS DE OUTPUT (AUDITORIA) EM UMA TABELA
CREATE TABLE AUDITORIA
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(50),
	UF VARCHAR(50),
	Descricao VARCHAR(500),
	DataAuditoria DATETIME DEFAULT GETDATE()
)

INSERT INTO CIDADE_HOLANDA(Nome, UF)
	OUTPUT inserted.Nome, inserted.UF, 'INSERINDO DADOS'
	INTO AUDITORIA(Nome, UF, Descricao)	
VALUES('NOVO MEXIDO','NM')


DELETE FROM CIDADE_HOLANDA
	OUTPUT deleted.Nome, deleted.UF, 'EXCLLUSÃO DE DADOS'
	INTO AUDITORIA(Nome, UF, Descricao)	
WHERE ID = 6