CREATE TABLE FUNCIONARIO
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(50),
	Idade INT
)

INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Max',15)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Max',20)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Botas',20)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Botas',20)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Lew',18)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Lew',19)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Veteel',18)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Veteel',26)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Leclec',14)
INSERT INTO FUNCIONARIO(Nome, Idade) VALUES('Leclec',19)

SELECT Nome, sum(Idade)
FROM FUNCIONARIO
GROUP BY Nome
HAVING SUM(IDADE) > 33

--EXPRESSÕES DE TABELA COMUNS
WITH Cidades (Nome, Idade)
AS
(
	SELECT Nome, sum(Idade)
	FROM FUNCIONARIO
	GROUP BY Nome
	HAVING SUM(IDADE) > 33
)

SELECT *
FROM Cidades


--VARIÁVEIS DE TABELA
DECLARE @Cidade AS TABLE
(
	Nome VARCHAR(50),
	UF VARCHAR(2)
)

INSERT INTO @Cidade
SELECT Nome, UF
FROM CIDADE_HOLANDA

SELECT * FROM @Cidade


--TABELAS TEMPORÁRIAS
CREATE TABLE #Cidade
(
	Nome VARCHAR(50),
	UF VARCHAR(2)
)


INSERT INTO #Cidade
SELECT Nome, UF
FROM CIDADE_HOLANDA

SELECT * FROM #Cidade


--TRATAMENTO DE ERROS

BEGIN TRY
	SELECT 1/0
END TRY
BEGIN CATCH
	THROW 51000, 'Você dividiu meu ZERO', 1;
END CATCH


--CRIANDO UM CONJUNTO DE COMANDO
BEGIN

	DECLARE @UF VARCHAR(2)

	SELECT @UF = UF
	FROM CIDADE_BRASIL
	WHERE ID = 10

	SELECT *
	FROM CIDADE_HOLANDA
	WHERE @UF = UF

END